---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: temporal-db
  namespace: temporal
spec:
  encryptedData:
    password: AgBM8DqDqCRI30+yOF4aqg+FzoOjpyBRuHatECU5O2NMMsEHIqu9zUqGPhvBSbnyjl7IBWZlBRC4M4K7I0mTzYOTCtEsl1Tkj6319K6s60VWkkbNCnycNOXq1VcxTSYGXhRsld32HoZete4jNAlwiMRt5clirXJDWI4gJS7OcIcZ6Zntluj8wQDS5Xv3kAjEyFcgO58i3ZS6gnpEfp6g4BU8hn6esRV8+F7zTzeWqKwiuVrzSys8fWofGUZINHOB0ctl2DxzyEr35ZexaWQS5rIr9jGSqANPD8GL0EB9JEyGk9mRUzQSU6QKRGJCAcQGegOrwY0S9CpZUqnyJsMv7i8eBu2t9nKwORkZSQgOT4LD1GozzqPFSHD+gf7Y0uROs/ALAXuP7MHlM/Bu2DpitrGH3+oKd+V0DCmCL7tazEyCHStwnPmstXkPUbRRD5V3Ayhy0TsVt1ucZ7MEwOiaBf9PBsgk69byd29sm9WsZEVKYJKhQD5sGy2FG3Y2MO6Wm0sLrcJ770anuoMRss//PVBKAQ2n3QLIoz31/x1Kl1YoYfShSmrvhdbV5Amkh7azVD9CKuMQLjsPGPw/+lGGa1ZKNubBVu8+r0RFT8MFBF7Lek5fyPAGDU5GNcQUcJUKFOmcddUdxIAWP4hz1LLOVXjcq8dn2gEfV2/a3w+aOZjPi9v97c2DJCGbBzJzJnSL9TDd2/ksnSYmjY2Yy+mK0k11FhZsZM61Etm2tqCbXm0V
  template:
    metadata:
      name: temporal-db
      namespace: temporal
