---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: claro-ai-crm-db
  namespace: claro-ai-crm
spec:
  encryptedData:
    password: AgBneoT1ALwrv99fxvVxHPwFIX91Sj6fWZLmD63g5ben0WnAw28F04ktFGL2mq6Xjy6AwDNnT6kG/7XdkbevQuDfiqCjms/i1U3HwAs9ia/DggsNtGc7DsEzQmChdN4q9kaGy/k2wSPLBVvKhx+khbYTssbJ98fI3id3n1zZJD+f2fQZ4QNAbL9CreVRZ7nQbUo/wzt52oPWARqTqk87mesrzIhKtOX7KAvfOZCu+l3+k+xrnVUXXSZ2mLtsZRVGdrbSyOSOZxcv5I6Ce74PIx6CqCmoMNrV1w8w5pzOSH/gmQ2GAB1yzzt4E8CVl6VQjxfEBa+tHsCy4IpsgrSntrOhUoQbPRSOKUXAAlMiOIhoeCb3lqCqKo+AfMk/95tA580du7R/H5tUYl9n2z4Q+JAL3QWlCyftpyIfPnRZOU+gtBUqaianMDo9Zx1SCYR+OHaZbFv9obKxJghjJZzMcAngXWj10Oo2OHVL2K/3WQylwJe3QeSGl9rGDx8iI0Ol/26tKDREMH6O4Ei2NbNgU3ZI4evDFCMhkvDXeWJqvSc66vD5IzLW6v6znhKG92ehKd2IK6nFTfQkJcVQMPPhCZDbjP2haeROqKO0TqnWX4+AkBlrsKRyUJSNmFKAH9NymbIicv3UJIiaKOcnb8eWQ4Un76ew4wZysfMrfFi3YhB8PqoGJ8oO4bV8in7GMKQfIb31QKL6HIJdgd70Gva7A4q0nFlSmMQoc9zoqzKRHlGp3A==
    username: AgCbnBDOZFzPlQdicOknBjaXTEwK0sC1vBsBVttBnbluW2/mwJBisArtWQV3ZkQXfABPb0Ojli6YRXowd47+OrQ6AzktjLa99zCSiFhZyda5m/yhQ+bNP69ezF5j5h+UgNULZfiKfH4CLRbk1drvmfQg1AKErd9+/Cp7tsoRVNUr1/oBKLJ0GLI1aZDKL4kPQ5OeWoL+qbBpJQXj6y6GNyIyKDAT5bJT62nsFl2ozB4j1J6qEA16rkM96S7F7b07PY2JNy6YJQV8oTqg4/k9PKBL2fAi1HeqYkbuCloCdsTwXm04hk/lFdAKiD1F6aG/NJfSSdkwAOCOaXAxp/WdTAGXhh06GPk82PbCXw6PUnBNLr15nWV+X3h8gnWO9AWnlJROXvqq8Q7h6pOMfWJAy32JPFHvCE8tem1cixvRxXaa7palyZ4bkxoCjd8v3qHYtnW1QJJ3QnsQKLLkEBwoyDFy+u8ApR8iMKym0RgOoVgE454SWAAgi7RTq2H6pOsVcSqaXCh0uJgOEtbKcL0I2602C7l5tISQXGpgdJjYh0tlSB8sOVSLgf6F3ZU2KZ5dz/L1G8GV4pAPAN8MaIhoHlpKaghU+SAm5QM5GIkLHkThL1yez6i+7BCwFLa+zpWFHzYWgdl5CGvqNFpPo2w/fdcWwLU8RXXcIEcqlXCw2BpLp8E6kqi20Lx4wFTmCT0czl4kQEv+ezp4o4fkJfY=
  template:
    metadata:
      name: claro-ai-crm-db
      namespace: claro-ai-crm
    type: kubernetes.io/basic-auth
