apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry
  namespace: registry
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - registry.internal
      secretName: registry-tls
  rules:
    - host: registry.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry
                port:
                  number: 5000
