---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  encryptedData:
    runner-registration-token: AgC9/anMARoVkK1uuLa+Z3UGMHvIusyS2epD1XyPI8DCafEq8CW42E8NmDbTvbCKNV95aJvvRpBWfEvOYkWn1BOE5+1VElOR7xmthn1L6/xPMqeRTCCQbPm+XKZ3gFdr0Nl7Z5BNMYP3N2TUoEsYJuCg9+r3azKshMVEQuxNIYJHsNYVBwxAjAYjIRoujkMUydH7Mx8doY6c8kTxYT5Le6TFl4PsAbBxNknoXkgXUqzdgPFDO65XIu/1Itysu+l9Grm00H1NWo/hIHr/UbzE09Go4xi28086Z5j5kw+JEchKcwj/zBbxxnWEYVNzDZMmQGvILlWVi3H3ucfKhLTho+Ocqxo/lbuXpyKtVp6FI6NaniumTfA+RWIS8fncOvA+FUufG1hMFC2xdb62gAbYout+D3VAwDcQ1PcGRYpLt6n7v+6D9a3LY2udX25cMZHWKQVzvKQRjWcRJLwWIfFiNE/HSv2uW16Afa0ML9EkrFu17zWcQ7wx1qwiY6ysTFQ5Lu/oQCnkqsV0cMbRUbFvKjl1zj3LBN4+Xplw550sParm6e3g5phrecN4DJl2DvLk6oQyf2f9+47QZOHIGAruhi2gH4Ess34h2I2Rhs7PmY0eOUuMRqGWW9ZDwM4Z6dUSfCVi4tCmwKA++oO0LwK5hpZWR/yRUH4yJQVbcQNJwnTwp11u9vg2Gm5etvuGtYuhxro=
    runner-token: AgALdtdxThMF4mCQ0WiA2MYYpy9w3MUxUmCZHfog4wIL1SMJKeXR3R76Sfbhpx49P6GXiOEL6lmhGUVATu+kppeuP9LK364qNfK3AC9SACNp9DOE+RE0ku9FsGSgbdFqZ7tIHY4Pr85WkQvaiyz7kbKx0tLqy44HAM2U8guRrTC2txjwsvxjuC7FfzNnB5yXA6DKMVHuF/kjD85BFH8rp3gfRDqLymUGuZyoYTLAmG6Y9YBqyw1nhLnAvPo1GCYEoOGgmzhZterg8dX0pcCXoPgEJFlMv33hDl4VWhFOXQU2Bd+CUAsKpoQQjirIu9QgG1/rMEpMgt75o1WDrBm/sLL/+ACHRVHfl6rXOkgHqQjd0l2uYQdM2h6WKfLTCjjE796eYwIElU4Xvf2WXBxWnbQCjtc2EVOBMeIqG0S8mipXGJ4w0FZWuoldh/o6OztRqKSObX7HNhF2bIl1ak1gVl2GiQU5wrXaOmx5INhDIodA8EGVXSXBBBtwtYeSDEZK4wqczcit5KJ8z8gRQFBYARK8Xx0fDN5xTYNZRNpMyD7Sa5pIuAGIFDC7TsAi281oDZf3vgHlnUluFUPAYjsCMwrvp1eTSEsmpBwBVIWErOeqR64HgpIcg0CQzkIgtjhDJpMDcpb4nMUgUBU/L73bLL31zXEFlY02OVhSUWFPWU/m77g1h5BsA0k6xp/ONSiPcXmlsX4j4RMtuXJo91UDBEKM/oFfAiyzXFKLxbtH
  template:
    metadata:
      name: gitlab-runner
      namespace: gitlab-runner
