---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBs2LUp06b5NTKQxB7DozVclCNt70VjoYV4SDe2m6wgvM7ps9V+YAy21/v9flM5HTNiuUaJSZ4zfexIic4ezAUmr7v8roUfytCGOk6g0Rq3WVVF/7gAhEA5A2XxEYI4NA/NfQ8PgJAwSu4D5IPpJMMM2TGmbVGbKCyoG49RUxSyzkpu13XzRbFL0VgXNdMegpN4nSPb/rxt0KVkMEchQpCVf7oCF6MYm9OT2eCw8Rm+js38kJMe7TQurMw5DxNUl+cQZtCWbOrSavvCqvl4v4ltZx92vdq1EDXUQ/3Mzh7NMV+m+qt5JU5jCqzcxjcKpFVi13v5Qu328maweOZeS4MwG4W1zrUhfgyfCpxh6lelGPxpTGptz1U3Prg3FWWouKTMK+ekvY+D2BgeCGzGrjAseiHfvAQqxEFSsz47Fy8dX0DJlxTWpIXznTJMrJMdPdcCiK/2EIaI8A9LloQv20VmUXlQWHnhQmt21IEeKSdmG2HzYKDOJPy17F/aD18b+OqLqCHyma3EGsthHc/MarPjDmS2oSJHKAi1Gg9ne/6f8MWNoKCfd5Rl4Re9hhLko6dLtBHhuY/GiP9z2FwmdrP8/yN/rCJ1laabQCaI8sT+62GpMh7vnUPBO1FYkchmDwWA9ofp9eY1jqvyER5EG02bARnfVDHEKeG69jxrNR47aXXUv7xhumX9nXqf03bavFmjKBSyspyrlIaq
    admin-user: AgBAOP9B6dkIr+Q5BlU+ZnAWeYsZnl02gLy7rcXI8fj7YjcCYVNcXe87HRJmtQBuGdPC177f0PQwcjGtkgN7/j/lFh5L52JjqJqrAj5Es8n5WiLkLbQFmBjiejnCuJYLzNxzS3SOq3RYHSXpnk0ZUCUW8fHVDQjI3NsY4DL0znG5bwU31Qx8E7wmyav6AqAyjYvju+01LGPSB0GpVqjzRDTCGIldtYwO/1wTyQ5Dpwf0/wPiUdW0uPV6cO7wLjcF9Ynu4M1iF0AJ+PE1lhP3WcIv5VKl9iPeHQV5KR/IB/C0ym39vyfeWDE6p118J/4ycYHpE7pznu1BpiMc+3hzu2Qhe3Nm5fOv/o2AWrNfSWaMPdigZE2YHlns7Q9Hl3DWpQjqRCEFTRUHKTa5wEx5SbNNPN+pZQl69ROg0Vjgbd9OrrFr0p1pF9rYErEd0ZHWjmi03winQnVwk2NFGF1vj8612PN01z0GBvmH+H2svPpiBbvVaU9JwTrSbiDA5decQoIBPOKDE78F6Y9CCOebI7kmEXKNTn75EokG+88YoMwHYZ5R0coVRwsUe/d/uSifu5rc55v6vdX0QA0aiuR+XR1cVPjppnGh+Gikxtme9zrkDghHBstA/afWJXEU41zNTiCBrsbu1xhZDk3qlKVViD/2ZM+6NNvxeQDr5VAgxyUQMFJfw86tbjY+IzrADORlJ7BQbeM2WA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
