---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-db
  namespace: n8n
spec:
  encryptedData:
    password: AgA4tOSvjXzbKfStIq4FmrlWweurMtSugp81xyBmTAzPW3ZOFVmgEm/6YGBCbECenuuwYtD0WjKUUyef/r5O0Aq+96tqDdMQw1SiwDIqmtKeJvzqcLN/xnGZpMn4Y/AMjkZHUsbW9xrtlR3jVOom3TzveA9w5HAUZ8x9jFcfRpTy43bCpxKC6NBzD6zB3z7TkrJ72/vt/EDI3A5dLWxO4erPEMjdvhGsxwoXcGNijGXE3s9TiE9Iys3v1uzzBverNO75DtS9EF1vYU092KtcY96X+dUHoT9hYrBJUQ5ZdPjUtVPa9ZNM9vqDOmDdCVhAQ8bEqJXbl4fOZCFWFzQCKvC3t4N18bwXB5/CEWyYGPK2IhGn6sCZjXhjK741EijUH1oGujqOICkCC6xzrJS6OTjaMWci4bZiRQh3sL3YdxFvYkPNv/L85pqQ7p6qrcZX7rwbbDnjW6hUSsupLFuvpVefojvMIlewViN4+FqVFEidjp7oe7/PBSAE1OH+g/qH8ynzN4RdlS1Rt2gLz5HkUShq0b2UMOSxkY6qY5vP8+EW5a/vkJ8IHiIjrD2LdUBb0k0psYFdXEJjdl4Th4B3GFsbUoC5SlW6VOD3FL+/LGMyweRxTMJLKpwsfsHEHiLSfpQwZNKFzdOMhZk6hMHHiQHYHiOmYPmSwQAfgY5TbkonswV/+m2hhepXSYN+j0x98CQN06WFRv+EHjdwIvSi0yiohHrya7NkKbe2rBLEF21r
  template:
    metadata:
      name: n8n-db
      namespace: n8n
