---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgCVucVmJdhYfy96mHFeJXJRnCaY7/ybjK2VwqXde/6EPM2ziL4WfLXbHPim1v7vaEXffLeOXiU3iKEJePhgtxJkEvHdJbTmiVs9xWFF6m9/38IBeYszLM/nS9fATP57W8UgIgY/l/ZVezWSi/QpFLeCzs5BRpOqKfadnSTS55ecOu+1v4dxQmR0cTq/7vfA1dsBaIHsJT3kUtPtYGCG5eFV85Zf7LyKhl12Lom9HjlPSexL0bQbEqgzhJp8wt5/ID5yDdM+0Fv0hm+zvMDZRvu2xs5zIhTc366Apc5fMbXUdVIODVlx5AT66Zzh00v1uASgrHksA75cc1JSUt53eOBzn0DLZoiFYH7ADKmzFs9HadmGpLlkvweo0UmuKsw4Ctu0vq3AOqcd0Dq+WHzr9Nu13g3tZua+8KFD4y7FKjcb0JqGJu//yP/Z/y420DX/nEWaYlMzqw65vYkSZfjo0C81BFMuTJ/MK3SAIj2/aJ8JvAa02ovhuJZ6EJcWCOx/yk6IMeRi+ctdvsU416dL4ntJAJa6l0PboeZfnlQk8z9T7xX4tMtJQsXOVYjlckixgPZN8p8FZQpfwLfcQpunxsy+PImNU6Nm+qIVC3UqbuV6uwBviSzDDil6BeedC8YREojL0dLqCV/gvxpJGgS5h67CBPXVyg6AXcF5Bo2OEHrW8qnIm/3AdY8aSO3xXqxSa8eVtMk43BJ2Kmu9CbD+CIJJR2scziM93gnQKIXec7o9s2sFKPChxqmJ7Vn4AlSpVWYgqNq9eWXEcwfnwW+UK9k2
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
