---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-auth
  namespace: registry
spec:
  encryptedData:
    htpasswd: AgCtoxmRUi8YZ3NE1jKIYRogeiMybSL+JaPqatg7mae+IHE0EhAuraNpXgsrRxdc+0smQNymVgGPJYPOmn6v6MjjYJc+TECPP3ZqwAvpD/mwJ3pDN71gxIV+lCtPe/P5I2YHBmTamgdX9Z4jrDvsk28gEaDiTcInghvNI15ob56IH0T9QksLLkf7xTArf+Uzuo7n5CmHIgbrUNzZasa9Idievv2UU3u8SWhWE968HdM0XrrYYNOIqnur0pUYaWPJedQEru4dz2b2F1whA7iVGwsgzP5mD0hkjwIDjlmppZlXd2/jMrKtd+XaB0JYo9JPfjvs78oPidOh1oJ8NqH8p+Kdrkbt66bh1NXtBoz7M2P4HuKJyGhQmQZrfOC+ngqx8UYsh58BVPdjip36Wx5cC2oLVAF2TZY4tqJugLdzWQur3TQZAYKeEm0Z4XjA5mQ3E63Z3M4T2NdPj7SUI5hivG9YxxhzYFQxO6HpSkLeiojkzothlnEjRxLYwDIeuC3jrLMCq0CF1pC6lU4MX9Q+FAtJzUTrJLYC131ChlCvDTwVzwLLbqoyzR14LVSIxcDKvpHO80Vf0Tte4NyonQAe464m72IE+hfbulR+HCE3QNmALu+v4+ssiDaea6JtmsFV1jD9STyopMVjnQTmtJ2W9OEVy/lB/B1zUztMjH7l0RY7sMizQ/7buEX4Y5Zt7pGyOVaitfltqBODPBuU+A3wtWEoJUce5L4FLswcS83nMug+UoFWgA3xZ2QgHDJbDpJ7ZcAkvnyYH620cIaxYkjUqBGrseDshw==
  template:
    metadata:
      name: registry-auth
      namespace: registry
