apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - postgres-authentik.sealedsecret.yaml
  - postgres-superuser.sealedsecret.yaml
  - postgres-claro-ai-crm.sealedsecret.yaml
  - postgres-n8n.sealedsecret.yaml
  - postgres-temporal.sealedsecret.yaml
  - postgres-rw-external.yaml
