---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-authentik
  namespace: postgres
spec:
  encryptedData:
    password: AgAwVbHFZqKpLhdMJuViYVbL4Ee9YhsauC7lKPo5P7Cg2QK4WLIhWn8YfPXeoczs4r2fX83QRK0M22Qi9SVnIrS2CqhX3GWdZrvlzA3ymUmnBEA+UUDwJaOmLehnZiK0UJsCCihVsPqKZU70qyV0MJXywtDYZFHfmlLnEQQc/IbWh//5+7t5mfXaQ2Ad1ZAxZQVFNxIZ/gXHv684ummtSlu+8/SC+g57EYRsSYg5/FSCnUy7QeTkV4U6KLLCdQk4fXzo3Jmqxe1FvRMV/azjXUs2nImhbseTc27Ug9oBXULyLbDg0bHvsznleU6Mtz/laRqZMeIStNCRWsO2dXwpeYO0l+OszFZ6uTJ1xVIhnKPCxELc3Vx/g7JhVlK0ZkPqtG2jB5fDkXFkvGzBs0lIu1gYH2xpWaFXHdClavcaze6omQLYw3afE3Xt1XAoHEIiVUT5mVfBen5Nqd8ImJhfSlirY8UxU3huf92WVW/r5BySM2F+P7Z85NVM+4IhCwlOaR7PPu23Bs8vrvGcNGgHt4psV4rmgAQBvG2wMb7dwdzY4XcLm2i9GDBsL1a02V2ianbRDmjwS0m5+KWdf3BLMkCp7dS3lppBm8CJhCbLUcnCao35dISJQPw/thzLe6vO2cIju8yga2HCJtnHmKjUyW8eJmp3w3Sa056TTTTyn5vDbpCmF9NJ8YIHvLKMNNFcLpLeZyG1ksflYbbjmgVjuBrYn+B4PJTVqm7aKpz5/qgE
    username: AgA11tFuR+klKEEuAlu+qjPgT1uq4/PunIHMyJIDiAuZqFrJcbisd7mngTm9K4wxleyVTqfRO0/Y6opjxpAEuD5F2+2HMR602N2Ljl7bzgvxoKLj6woXziTTjmf9kKnDS83xqjXf6HMZpEbZn/JvEdZ0V/q0Hqa/5fvucKzupXCH+oilZvOZ4ZP5y+nZcgg5YuqRRkqNIlNU0BDTfF1Dofqna4rfurWSW2/kaXsCgxDwfUV4OTSvbXfgMMxsqLmPk6rtrzCJ/+WRWfiS4vjXoUQJ0KGDtoYWA5I0T0JOl7Y/Kyj7c4gCpJfb6dZvyU3fFWu6oBTHDLGs4fRiBWTvI6yx53LRC72KgdJB9hm6AB/nsnzYBtnx2GxdmzfasKb6vltzvZbCaURqSQoMUCrrzfScHEJX6MiC5O1UIUZ1ltnG5aBIRv1eLrnW/KdOAPR2EA4ZfEX3l6zdeWovqzgjATsBX0Z7Ur0gMPKIt4RTJLd0xWqEcuESFmGczhT0+cIIqu4FO4eO06A+X0dJN56G9c7Nsg8zmapDKFYfFh35GUUci1aCGdnR6UJQe4J11h15VIfWwwLzyY6wP0nDQFeVYOBd1ZzMskc1glzNyjE7QOL4w5nVb4XZDRUIxfHtYtAyuOdZaxCezMk1hyvo7aPrL1rS1u9SyKL8ywcBSw1O+AWZlRaO9mRy7SQELq267cQye9Fyz1ASpqj5LZY=
  template:
    metadata:
      name: postgres-authentik
      namespace: postgres
    type: kubernetes.io/basic-auth
