---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-superuser
  namespace: postgres
spec:
  encryptedData:
    password: AgBK/NMrxEeowp4tfUGrMe7/NnAhUQJ0H7rqeDPCjYtpCpo88wfQUOlMNCO7gN0L7Zs5PIsV+VTUpjCWo7/op9D2SPniQlq9XG4ZrjZvXhvfLzb4IAgy0FFbfpHPxhyIxB6UZYxjrZ+wJ8l9vjAW+iRURvnwlElxHaA9DZNxwtgm516MzSntxMTX0kIwU/UzVyO9zi1NW5ZaK6SRW0RP8YFnD81i2JmBecEoL1TawRVCJIzVlZaSmAujtqXNnOqOS6OSyd89bIKXecQViWr6CADVsdGHTH7/2k+ZcBMc7dqKotewfcDpEcnBBNZnBFhTawm04OT8cs2qc1mucKNJAoKKj6XTdJlUT+tiMxHAOoja3vtYtCBWGOB3Uh/AwYDhMuo2yYOamKUAAAxyhqBaTpeU/vpOc1lG7rzpLKPec3CHS8h6DRineoSuSmtqXwGRgz1rtCUf96nyzelp4k4bxqC+zDVGEzyQQm+8MlB7D4UKK9IA4MzsA5ZO54JLjCyJd69TMsG7ZneJ30/AkKOaT34wAjd+OyBG38MOn3UuCfugCF46U0Y47VfOpDpqd+izUj2rthYw5lSgo0/Ifszx8jW3S6RA3Vz80Nx7mfhXazhF8vEoIpGi8KEnlpDJwdZdNZi8A8ilSjwt3XJxNkQ2t2YVZ4EpbgkGgFpOkJxawPIIRiLyxY5yhKxfs4ldncehiXRLhG+ClDUh1NREUZ8J9c3jYiDOFt2n1Z5DuqxEyro=
    username: AgBEZ506DuFI9AfRUNkfkdiqVthcvVrl8w/1tr1y8nKI3R5DDVOBbZ7L6AcH9S94rJFNdw4L7nQGNigJ/lntsweFzzrNRwSGbEt5YdlV88jM3e2/JvReQqUtRdLoqbRr1w83phdOClFvfrq5wniX2zh0kvNTGKDoHgHeRphIsE8ZaigwZtmoXNMFFakWBfNXg4dk12Pydenm0nfz75sAuUQVldFzUujnxgO+Wjr2La3iCdQOeACxRsmSfJ3Gxis23bdcd4lqoW+0FVZfEn2AsVHqIHRRp39Lr39xFPPRopj962ixJut7QE1LlgA/Adp7HJjuZ+M/1JlMW6SGRjNsNPngKnxdu1CKkMHLjhl7xkl94KDM3dn/kci1RM7Vw3Ad6NR09iDQd7cb5CGgNe6oxkC/CF2a1pOSQR5pheaQtAiYdWD2yGRG/bBUN5YH+5goBKw7ageSPTDTEEmpKzlWU5jZ0W4ntg5F7WHYGBNJoOIaGXWdK5vJwBJ/h8RCJgH+3Tabf0urfkFYN/QzU+p4zz8nrwQ2520YRS/uNIuAfefWNQy3bmPi3LwUVhWAE590SK34Iw4acFmouJqqiFf5+R0CRNaPodryUBM830wYUgQ+iq88FderSPm9oRl/Bcke29BfYlVg5F7h5B+crLzFcKQadMWbTKNGC7b3mvi2x0OHUJSvnlZ/qiG9pMuwdh6u0OkmQa/x2qeieA==
  template:
    metadata:
      name: postgres-superuser
      namespace: postgres
    type: kubernetes.io/basic-auth
