---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-temporal
  namespace: postgres
spec:
  encryptedData:
    password: AgAK93tgnYYnPd+/UT0sGt5MNjFOJbtlcxuGKg74VLwow8Ym6vL/DL+WdTOkyucxrboJfg3UCz6QayXuDRLwnPZ4nviaz45ucSpKJrsiOj+MBIoMqho3wCW+2pnveeEK9SqdARVD9arW3qe+6m2BvBNMb2vBncA7Igz+5ab9fHN2abp+7Sf18ZSlyllKSHxJgSvvsH7+Lm8Yp0sO5bNjXWfWlKxKNAtQvNUkjfqXT1Eic34i9/ezEUssB+pqmpUBVa+dVVhltk1LQQ0Zlu/8UTyQGcMU6BbHy1vka2s1wfKGKNo81+vu+LRc4Ug4FSJZMvJJ3a15vWRrxrDD8Ne0nDbTVP/mvSOrYVY3tNkLn3m7UezlKdis2CeHSV+SNDPyKDfwJsYD5zambg6glg30NJl/OEU0+qAwjIubVEZmotRzDIoTn/FSH1mUBYIemqcxHbH7l4nVHL+Px9Xq/Xa+u2YJscA6ZJajXoL2ZkVbL1aCytSvu8fL++K+aRkghibFrOBD7N4KWHhMiHRK55ceWmef86+sBMkdllSRvi+wOuUfbebaSG6sy7bWd29g4D3mnrQpzP6BXhKjdxBu/rBYZgWR5wufMKF4yu/THstehdL1SFIdN/RKQ97PJz9qpVVlsVl/LwUaH66JiS/gmOGKcATK4aov6VKe1qwE8/a8O1uzg0kOTSSQLw6ICnOFnrXaQyeEkrBMONxf8nDR7hOEOkV16Jtpbqn6unxLI+QPXySl
    username: AgCYPiYT58oxBK547JpEsF4F8nr5uUn1Rrx22j4FnoLBML4rHzb1lPPJu5UVAhGjYSmZD77UqIlwJs70OcWI4IGPFMIAJD9mc1NgIeBNXPsAgmYswomK88Yo2+hHhNRSJ4MueU8bYwG7KLLunEf72jBETKTkbSU+Sn02QqY6runvULXd3islyfZ7I06T4HMuXdpgmq+AXRGO7S+f4h7T41mziM8eAP5tjoaNtI/4x9Fv5yECNleb7kBmA/2m/1Qb8ddMeQDMmRzWi/4rEHk9BiNXPhV8kELQJjR/WgRzPdGPwgjw2zzEc5T/tqhyc91ucZCvM9mgwZcwJt6UxYPlruD4fN6uUZ6OmBttxIDmkXI3fND18s0djQgrrCIPmw7h9C4X192jgEnn8fi26gKAKfdo6cZ1r6Cziw5BQWFtL9SqMKnqi7QfA4GzumdIfzwFPdt+sNCG2lTOTb+I2PciqdRTEYFpWDS7NsWSuBXw0eYvfdYqWCQbJAbT+E/5XrLSwNcl6K11bABaAXsyxlhrcEZI0eObHFuIcXdYOP1XVpln7ynGkAcul9qZho+8CVKm5d7rl+fBXKCdFl9rFA5De5RW/z5A0bUVN+znOE8MhDr7zw2y9zTGjZwoF1OrSceoLaCnJ1NhovIk490uaMyKRZ4bf/SbTL8/ZyKGyOAYUoSShk0wuswGYIP2Z5h+iJMxA829+YJhvX0tKA==
  template:
    metadata:
      name: postgres-temporal
      namespace: postgres
    type: kubernetes.io/basic-auth
