---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-claro-ai-crm
  namespace: postgres
spec:
  encryptedData:
    password: AgBYRdKQDMhKODllmWhoWJLiyw/MVBtTtfRv3pZnPRInNamr4zvJL5F7ibJbrHwvos5Yn86KUIUXVh0oQLwCfQybT+MTrPtJ3PnlrrcuCXJcfTn/47jprfJTrm5sEdeRTyWDh9You2I3ZEObdkYPVsFc+9EbFGqPas9G7bwbrvlRp/IR5zvbKGC1hOgAuRFd3JTX4c0+ZxvAE8ZfmYLJ5Ttq7BuYSsvFsGDiup8vvAr1Tcf8f7w4beOkvZ3d3Bd/bdKveJI/SMbadShNaZsNTNOkXzuxv717tL5ScgEBHdf328ASpWDQwGJ8jr5pm5B+iKq2A7e+jcLagdC41d+o0n59wosdmNS1RqZ2NS+QZMqwIN6/E/wn6K3oVo4RqNL5daO23RK79eob74RUTbM8Z7xthXtHIKtUxE0rpCtMoTIb6x6IRtpkpowPXJk+e6k5mFkWit6AbfJmgMiglXwW0d91iQutOknp84RISuUhtNwrCS9MbdG+6CSSOnPfG/5TH+rsxESfT8m77K3TJiKKXPmS3woR/2uFohJk4RWlCiSIUxPzlhVMPjUHP/5cSM3cYIN2mjrQnumCzEti69rjTfRyrJ7Sf1dzjQqkqM4crlrJCd3nW3FU8F0XWa9N6jTnxkfdFOsEEisVxW/oYfXRyVUGK4u3WKA8Pedw2635FzUt062Wec/NJQsQ5LQRR5C+je6fjJKgAsLe9RUi76/f8RS4OSxOAIvU42mDTmIlzHll8w==
    username: AgCn+Qf7CLKjlxCrpK7Y1YA470bIzOnB/5fb+0GigGw+d8p4nmTf2hqtbAmg0os3up4RszXMx0ssMPNo8dHyYmAZZb07f3SIX7xrqiToCpjBAskrqKD5B4UfRwBkBzrZBOtXZfqwIkvdZVl3CCj8LX5w67muUuSXAdkYS2drtShJAzTFFW/M1Mcm6Cd4E55Cfl1YpVSv9dp8tRhwp0rq3joc92sZXAjaQJyynLnKxIp4jQkNn5ekA9zv6VuMTTjElEASunzrm3xBhkXFttOf10CtWpKsMOTDuxHSvmHvJHzJ9CAhY3xTNVW+UzxUra75T7tJL9d4UE3N01TeJfF8Lq+ffIvcDxArjDxdsmShTD85VDBtewsYmy6kg/5s/sfy73o6VmGaQp53Zy5vUYAcf4vY+FBH+1PvRqCWPbPi84YVTw8P3Qww6KqCFgM+2XR/Yku7KOSHqACbEu8LEArJGrcj4/m+X1nb7LiP/sfB2ixInsd2ewWDF/AKkIOaz1LMJkiiWpwbQIHB+q4cLyuLC9JtR9ybkijP0gJXJyvG754HhjnH0adOl6yZuETJKmEDojEVSA6g+N1+qoAVXDu4BcGl0xZ0lrzcm3VOq1+1Boeg2GjUFaxq6vFOca0OBrbRuRHyscFmMoAeuD02hWxV3Z6xs3n2rt3uBKAh/UHoTJ8pgz6HmLaPde/bz90fCQ5DWcWi5O8v0CNq3XCeMTs=
  template:
    metadata:
      name: postgres-claro-ai-crm
      namespace: postgres
    type: kubernetes.io/basic-auth
