---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-n8n
  namespace: postgres
spec:
  encryptedData:
    password: AgBc6lKSaPYkEmH+7QJRRGD5ubOJCxNp0S4hJsKl2ZuUnCGknmG6g7aH2GuZlPriZ6IknM+mIQZQattfLoSy/I0qarlvg7B/ZKPPoUamSB/3TKcFhqr+T3Da7fv4yfBfR0OJQozI90/MIAqC34ZB/IiFR/WX9LYaDuC+TJkqzx+SMt3R0/TMNXheB+lDuOQGqPW2pbPVMJIDQMuWS8B9CHZQ5aH1gKouY3TpSa3RLu6CKaP1brL228wSQ6O0fjCerWz2p/BMM/h0PpUFgiOTi9c/v0ZKwIJxnXFt5kVFIRLHWMmVGia/6V+aoL5FzPFQ2/JhHXO8+pd9E8zac0BOfWQo5sJIjAMrPOW+li+eQpUqUAHPFCKw+uuzbYs7TJL6+Bjjf8gkr7ekUlnpQtclHh35n58065jFM+Wl2xirRd0a2HZF9MY2zMkfxwkXwcyenhAHd4rHUdn+G/A/0JSe/0cjdvtvUrE5tt3s1UKLxdnakgwUpEPS0kWL0hFUekuUxQITdCfXzfSt269T7cXi4Sk895BWjaldhHMUa7zKM2M351yCbLVeLAQsP5fl3OsFuq7q0UykJFaZZ0o3qa7h6N7ndLPzGvJkMZoVr6H92AGdlwuj/PeARdXXV6rW1BbwKwS4QAyQqRlDZ0RzZtNKWYKsUR2hZ9oxJmkIP0O4ga+PlfaOKddVkMXm3KbJxFdEk/29uIJ2u4bB3FMsxXOf4tj9eZsZ6M67AengEOhjGQsi
    username: AgCkAMFY5Js2XMyfqlc7aD2Emlj1MV1sFMmdu5jK+4A/fRo8rcJHTy6jjAsczBKTku8AX/VgQL8Cx43cDRJoFtb2+NzbgZEOckUZNH4xzvLKJ0TJyjXDTkm6Fn04RJWl0FtPX7WnHqGjNUtaKDxfYvLJcAkmMgOJPKh7dJm14ug2+qKjbMTQuuibqgvSCr2IqRu3O13SYOjcq7KQyns99UTQ58s4Jpxn1pOSHCCNY99iRLJFoWaY0kTqht6QMs+biq2kgzjG0lBFCyuB6mRPlHpBvGCFFjxlvp8AKuzS8HJTpZIFVaQ7AR46DhJMitPxejeD7YzbEx/6MR2B1IT56kgaoApBdru38AGDpxAn7vL06hVm+Ud4h7rxaa00rlce2NWMjViGgMQSZSPhcJ4DX5qzhU5V99ZbqeZxZYQtUKp2HUOpUnn41cVmYPvpezfoRpwo74OkUXmnKyMcdzqht6UyLAaScbmEGTxKhaaeBiOesdeRrbCEfWhkexk57Fv/XESzxqdoJ7BvoWqU+XhZ0RvHWJAlzOqTkn8qPvV8c+rB+pnzP+jsy+gGGbDUI30PtI05XiKmRug/BFCVzZ3wi/JHBFEjGXzxC6R30XLlf3wIUAXCYxbwxpjGui1haoGGu3Y0WVoYWSCfSeWxZ0bGkjxjX4YrJY1v9dtcIw5Lfonbj9G58jgURCRLDXUld5riboSA/KU=
  template:
    metadata:
      name: postgres-n8n
      namespace: postgres
    type: kubernetes.io/basic-auth
