---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-root-password
  namespace: gitlab
spec:
  encryptedData:
    password: AgBG05O+0ZO+7EbNA08LEj8QpKQYM1y+rAdGXfd4a1xHQKQgxbBoGMi3OASYzwRvpncw25+XoTvzNzRAXYQJZJQFQM0hil8EsxbUFQXd071HuvmkXMhPFfZzzFWQF7FzPp9W3B1g7G3C3EqqIEGnG6/HLRZE1pN/Mzt7gL2wysD5ehk4HYH48FdL9BskCKcj33QaGWHuHtcJSm0RkZNC67bIQgH1oTwTQwtIjUT+2GQeHQkmPAcOT6kkXgCx5DOVtgvI3XgI11vHcW5Hq2/bUXyd/f5tBmk5vIcUEKlCYCfxTsVDJnxZlea0V2V5MMaLW4nzv4NuCwrZuEqCluLsZh6qHYF9ozfDn3DyxzVLn5IVe9gX8mVzGxRoZlafqBGDuwdhOOeW46IKEnnyWobCkP5QIUdc9CNFnxdphQTpTrFmk3tPz2YFVWwtFDbgMq8TtEyzUuO263BhMJHSxtcYv/noC9qOT838MeY5QrPJj3wlcjWw41ucukuf0YHdCKpn0SSBeA3vL0sDYCwkWL/DPjpiJLpytbc/NhKLQGfCOyFX60SLq9erJv/Kgj33MroftwSXHOOUHvIaswH5eXqVNxT1JtYdasVBDVNpL6NwUlk0anefcyrD2DZAYotP3F+tnHIeAa9Kpl0HU8pqZnckzQZ8MPOLTK31NldmWdrtbCWWGFUB4Qf4eN1rWAgWvOdNjoaWlRmnc5EaoYJRh71H9wg2BEvYCSMU/AcdYTQpVlaZtQ==
  template:
    metadata:
      name: gitlab-root-password
      namespace: gitlab
